name: Go CI Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to main branch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'  # Specify the Go version

      - name: Run Tests
        run: go test ./...

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Install GolangCI-Lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run GolangCI-Lint
        run: golangci-lint run

